name:  Continous Integration

on:  
    pull_request:
        branches: ["master"]

jobs:
    test_contracts: 
        runs-on: ubuntu-latest
        steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v1
           with:
               node-version: 14
         - run: npm ci
         - run: npm run test:contracts
           
